version: "3"

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 890213
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata

volumes:
  db-data: