# Generated by Django 4.0.4 on 2022-07-08 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineschool', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=150, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(max_length=250, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='slug',
            field=models.SlugField(max_length=250, unique=True, verbose_name='URL'),
        ),
    ]
