# Generated by Django 4.0.4 on 2022-06-02 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineschool', '0002_registrationrequest_courserequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courserequest',
            options={'verbose_name': 'заявка о старте набора', 'verbose_name_plural': 'Заявки о старте набора'},
        ),
        migrations.AlterModelOptions(
            name='registrationrequest',
            options={'verbose_name': 'заявка на запись', 'verbose_name_plural': 'Заявки на запись'},
        ),
        migrations.AlterField(
            model_name='schedule',
            name='students',
            field=models.ManyToManyField(blank=True, to='onlineschool.student', verbose_name='Студенты'),
        ),
    ]
