# Generated by Django 4.0.4 on 2022-06-02 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlineschool', '0003_alter_courserequest_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationrequest',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlineschool.schedule', verbose_name='Курс (ближайший)'),
        ),
    ]
