# Generated by Django 4.0.4 on 2022-06-02 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('onlineschool', '0004_alter_registrationrequest_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='courserequest',
            name='email',
            field=models.EmailField(default=None, max_length=32, verbose_name='Почта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='email',
            field=models.EmailField(default=None, max_length=32, verbose_name='Почта'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='courserequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='registrationrequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
