# Generated by Django 4.0.4 on 2022-06-04 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlineschool', '0006_alter_registrationrequest_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courserequest',
            name='user',
        ),
        migrations.RemoveField(
            model_name='registrationrequest',
            name='user',
        ),
        migrations.AddField(
            model_name='courserequest',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='onlineschool.student', verbose_name='Студент'),
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='onlineschool.student', verbose_name='Студент'),
        ),
    ]
