# Generated by Django 4.0.4 on 2022-07-01 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineschool', '0008_remove_course_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, to='onlineschool.student', verbose_name='Студенты'),
        ),
    ]
