"""empty message

Revision ID: 76320d80ac14
Revises: bdb1a352b36e
Create Date: 2022-05-28 13:45:22.800255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76320d80ac14'
down_revision = 'bdb1a352b36e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookmarks', 'blog_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('bookmarks', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookmarks', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('bookmarks', 'blog_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
