__all__ = (
    'HomeTemplateView',
    'SearchCourseListView',
    'Contact',
    'APITemplateView',
    'generate_token',
    'RegistrationRequestListView',
    'RegistrationRequestDeleteView',
    'add_student_to_group',
    'register_registration_request',
    'register_course_request',
    'send_registration_link',
    'CategoryCreateView',
    'CategoryUpdateView',
    'CategoryDeleteView',
    'CourseListView',
    'CourseByCategoryListView',
    'CourseDetailView',
    'CourseCreateView',
    'CourseUpdateView',
    'CourseDeleteView',
    'ScheduleListView',
    'GroupCreateView',
    'GroupUpdateView',
    'GroupDeleteView',
    'StudentCoursesListView',
    'ScheduleCalendarView',
)

from .main import (
    HomeTemplateView,
    SearchCourseListView,
    Contact,
    APITemplateView,
    generate_token,
)
from .courses import (
    CategoryCreateView,
    CategoryUpdateView,
    CategoryDeleteView,
    CourseListView,
    CourseByCategoryListView,
    CourseDetailView,
    CourseCreateView,
    CourseUpdateView,
    CourseDeleteView,
    ScheduleListView,
    GroupCreateView,
    GroupUpdateView,
    GroupDeleteView,
    StudentCoursesListView,
)
from .registration_requests import (
    RegistrationRequestListView,
    RegistrationRequestDeleteView,
    add_student_to_group,
    register_registration_request,
    register_course_request,
    send_registration_link,
)
from .calendar import ScheduleCalendarView
