version: "3"

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 890213
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata

  web:
    build: ./blog_project
    environment:
      FLASK_APP: /lesson_5/blog_project/app
      FLASK_ENV: development
    ports:
      - 5000:5000
    volumes:
      - .:/lesson_5
    command: python /lesson_5/blog_project/app.py
    depends_on:
      - db

  test-db:
    image: postgres
    environment:
      POSTGRES_DB: testblog
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - 5433:5432

volumes:
  db-data: